name: Auto-Tag and Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 18.17.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          registry-url: "https://registry.npmjs.org/"

      - run: npm install

      - name: Bump package version and create tag
        run: |
          npm version patch -m "Bump to %s"
        id: version

      - name: Push tag
        run: git push origin refs/tags/${{ steps.version.outputs.new_version }}

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
